#!/bin/sh

# install the gpg keys

MAIN_KEY="/etc/apt/trusted.gpg.d/puppetlabs-keyring.gpg"
NIGHTLY_KEY="/etc/apt/trusted.gpg.d/puppetlabs-nightly-keyring.gpg"
for key in $MAIN_KEY $NIGHTLY_KEY; do
  /usr/bin/apt-key add "$key" >/dev/null 2>&1
done
