#!/bin/sh

set -e

if [ -f /etc/apt/trusted.gpg.d/pl-keyring.gpg ]; then
    rm -f /etc/apt/trusted.gpg.d/pl-keyring.gpg
fi

if [ -f /etc/apt/trusted.gpg.d/pl-devel-keyring.gpg ]; then
    rm -f /etc/apt/trusted.gpg.d/pl-devel-keyring.gpg
fi

if [ -f /etc/apt/sources.list.d/puppetlabs-devel.list ]; then
    rm -f /etc/apt/sources.list.d/puppetlabs-devel.list
fi
