#!/bin/bash

source /usr/local/rvm/scripts/rvm
rvm use 2.7.5

set -ex

# Workaround for https://issues.jenkins.io/browse/JENKINS-64000
git fetch --tags

bundle config set --local path .
bundle install
bundle exec rake clean build sign ship --trace
