#!/bin/bash

curl -u jenkins:$ARTIFACTORY_API_TOKEN -X GET https://artifactory.delivery.puppetlabs.net/artifactory/api/archive/download/release-engineering/ci/puppetlabs-release/RE-13966/565c0df?archiveType=zip

ls