#!/bin/bash

set -x

VERSION=$(git rev-parse --short HEAD)

echo env.BRANCH_NAME

mv output ${VERSION}

zip -r ${VERSION}.zip ${VERSION}
echo $ARTIFACTORY_API_TOKEN
curl -u jenkins:$ARTIFACTORY_API_TOKEN -H "X-Explode-Archive: true" -X PUT https://artifactory.delivery.puppetlabs.net/artifactory/release-engineering/ -T ${VERSION}.zip