#!/bin/bash
##
## Jenkins parameters:
##
## PROJECT:
##  Name of the vanagon project (Examples: puppet7-release, puppet-nightly-release)
##
## REPO_NAME:
##   Name of the yum and apt repositories to ship to (Examples: 'puppet6', 'puppet7', 'puppet')
##
## REF:
##   Git ref of puppetlabs-release to ship from (defaults to HEAD of main)
##   This is probably no longer needed.
##
## NIGHTLY (true/false)
##   Indicates that this is for the 'nightlies' repo

source /usr/local/rvm/scripts/rvm
rvm use 2.5.9

set -ex

export TEAM=release
export ANSWER_OVERRIDE=true
export FOSS_ONLY=true
export PROJECT_OVERRIDE=$PROJECT

export BUNDLE_PATH=.bundle/gems
export BUNDLE_BIN=.bundle/bin

git checkout -f $REF

if [[ -z $PROJECT ]]; then
  : === ERROR: Cannot continue with \$PROJECT unset.
  exit 1
fi

if [[ -z $REF ]]; then
  : === ERROR: Cannot continue with \$REF unset.
  exit 1
fi

bundle install

case $PROJECT in
  puppet*-nightly-release)
    # Normalize the NONFINAL_REPO_NAME by stripping 'nightly' if it exists, the assuring it does.
    export REPO_NAME=${PROJECT/%-release/}
    export NONFINAL_REPO_NAME=${REPO_NAME%%-nightly}-nightly

    bundle exec rake --trace pl:jenkins:stage_nightly_release_packages
    bundle exec rake --trace pl:remote:update_nightly_repos
    bundle exec rake --trace pl:remote:deploy_nightlies_to_s3
  ;;
  puppet-tools-release | puppet-release | puppet?-release)
    export REPO_NAME=${PROJECT/%-release/}

    bundle exec rake --trace pl:jenkins:stage_release_packages
    bundle exec rake --trace pl:remote:update_yum_repo pl:remote:update_apt_repo
    bundle exec rake --trace pl:remote:deploy_final_builds_to_s3 pl:remote:deploy_to_rsync_server
  ;;
  *)
    echo 'Error: Unrecognized value for project.'
    exit 1
  ;;
esac
