#!/bin/bash

# Builds all platforms for a vanagon project
# TEST
source /usr/local/rvm/scripts/rvm
rvm use 2.5.1

set -x

export VANAGON_SSH_KEY="$HOME/.ssh/id_rsa-acceptance"
export BUNDLE_PATH=.bundle/gems
export BUNDLE_BIN=.bundle/bin

bundle install

# Get platfroms as an array
PLATFORMS=($(bundle exec vanagon list --platforms --use-spaces | tail -1))

# Only build debian platforms if project starts with release
if [[ "$PROJECT" == "release"* ]]
then
  for index in "${!PLATFORMS[@]}"
  do 
    if [[ "${PLATFORMS[$index]}" != "debian"* ]] && [[ "${PLATFORMS[$index]}" != "ubuntu"* ]]
    then
      unset -v 'PLATFORMS[$index]'
    fi
  done
fi

# Convert array of platforms into a comma seperated string of platforms
platforms_string="${PLATFORMS[*]}"
platforms_final="${platforms_string//${IFS:0:1}/,}"

# Retry build up to 3 times
for i in 1 2 3
do
  bundle exec vanagon build $PROJECT $platforms_final && break || sleep 15
done