#!/bin/bash

# Signs and ships artifacts

source /usr/local/rvm/scripts/rvm
rvm use 2.5.1

set -x

export VANAGON_SSH_KEY="$HOME/.ssh/id_rsa-acceptance"
export VANAGON_SSH_AGENT=true
export VANAGON_FORCE_SIGNING=true
eval "$(ssh-agent -t 24h -s)"
ssh-add "${HOME}/.ssh/id_rsa"
export TEAM=release
export PROJECT_OVERRIDE=puppet-nightly-release

export BUNDLE_PATH=.bundle/gems
export BUNDLE_BIN=.bundle/bin

bundle install

pwd

bundle exec vanagon sign
bundle exec vanagon ship
