#!/bin/bash

source /usr/local/rvm/scripts/rvm
rvm use 2.5.1

set -x

export VANAGON_SSH_KEY="$HOME/.ssh/id_rsa-acceptance"
export BUNDLE_PATH=.bundle/gems
export BUNDLE_BIN=.bundle/bin

bundle install

PLATFORMS=$(bundle exec vanagon list --platforms --use-spaces | tail -1 | tr ' ' ,)
PROJECTS=$(bundle exec vanagon list --projects --use-spaces)

echo "$PLATFORMS"
echo "$PROJECTS"

bundle exec vanagon build puppet-release $PLATFORMS
